[package]
name = "cve_2023_38646"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.4"
clap = { version = "4.4.6", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["json"] }
tokio = {version = "1.32.0", features = ["full"] }
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }